### ISSUE TITLE
Code repetition

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#10]
These lines

https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L181-L188

And these lines

https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L146-L155

Repeat almost verbatim, except a small difference.

Repeating the code, instead of reusing is extremely bug-prone. Avoid it as much as possible.

Moreover. Why don't you use normal `xa_store`?

**Comment by yaoxinjing** [comment]
thanks, i deleted this func, and use `xa_store` to save the entry in xarray
