### ISSUE TITLE
Unclear logic

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#11]
https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L92-L101

Why do you need to `update_key` in lseek? This time I genuinely do not understand the logic.

**Comment by yaoxinjing** [comment]
thanks, i have changed the logic of this func to meet the requirement of manpage
