### ISSUE TITLE
Proper printf flags

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#5]
https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L39

Do not cast variables to some other type unnecessarily, when using printf. Instead user proper printk specifiers.

For example for size_t and loff_t you can find them here: https://www.kernel.org/doc/html/latest/core-api/printk-formats.html#integer-types

For size_t it is %zu

For loff_t it is %lld More: https://stackoverflow.com/questions/13437758/format-specifier-for-printk-loff-t-types

**Comment by planetA** [comment]
And keep the lines shorter. Strive for 80 characters. But definitely not more than 120 characters per line.

**Comment by yaoxinjing** [comment]
thanks, i have fixed this issue
