### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#6]
https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L38-L44

Why don't you just use `xa_load` instead of combination of `key_exists` and `key_value_store_read`?

All in all, the that is what the second function is doing. You just check if the result is `NULL` then.

**Comment by yaoxinjing** [comment]
thanks, i changed the code to use `xa_load` instead of `key_exists` and `key_value_store_read`
