### ISSUE TITLE
Return -ENOMEM

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#7]
https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L66-L67

If memory allocation failed, you need to return `-ENOMEM`. You cannot continue execution.

**Comment by yaoxinjing** [comment]
thanks , i have checked this error and return `-ENOMEM` if there is error
