### ISSUE TITLE
Reduce memory allocations

### ISSUE THREAD

**Issue by planetA** [yaoxinjing/simpleDeviceDriver#8]
https://github.com/yaoxinjing/simpleDeviceDriver/blob/575ebb004b1771e8767032e12f068a7123ba28c3/device_file.c#L65-L75

Try to use a single memory allocation in this piece of code. This simplifies code reading, makes it more efficient, and simplifies error handling. Overall this will correspond to the kernel coding style better.

Here is a link: https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html

**Comment by planetA** [comment]
Another tip, you will need to change your `struct key_value_pair`.

**Comment by yaoxinjing** [comment]
okay,thanks. this tip is very helpful. i would allocat memory only for struct key_value_pair,which has a Arrays of Length Zero and a variable indicating the length of the array.
